kiva/kv-ui-elements

- kv-components/vue/stories/Styleguide.stories.js
- kv-tokens/configs/tailwind.config.js
- kv-tokens/primitives.json
* Build out custom text-h1, text-h2, etc. classes which adapt at breakpoints to match Figma spec.
* Add link styling
* Add a kitchen sink file to start working against in Storybook.
> VUE-570 typography

- kv-components/vue/.storybook/main.js
- kv-components/vue/stories/Styleguide.stories.js
- kv-tokens/configs/kivaTypography.js
- kv-tokens/configs/tailwind.config.js
A story that builds a visual representation of our tailwind classes by reading in the tailwind config
> DIY Tailwind config viewer for our primitives

- kv-components/vue/.storybook/main.js
- kv-components/vue/stories/Styleguide.stories.js
- kv-tokens/configs/kivaTypography.js
- kv-tokens/configs/tailwind.config.js
Re-doing this PR so the commits aren't lost.
> DIY Tailwind config viewer for our primitives v2

- kv-components/package.json
- kv-components/tailwind.config.js
- kv-components/vue/stories/Styleguide.stories.js
- kv-tokens/package.json
- lerna.json
- package-lock.json
- package.json
This prepares the repo for publishing releases to NPM using Lerna. I will do the initial publish manually once this is in main, and then make a follow-up PR for automated releases.
> VUE-521 VUE-572 Release process

- kv-components/vue/KvLoadingSpinner.vue
- kv-tokens/configs/tailwind.config.js
> feat(KvLoadingSpinner): Modify the animation timing for KvLoadingSpinner

- kv-components/vue/KvSelect.vue
- kv-components/vue/stories/KvSelect.stories.js
[Vue-592](https://kiva.atlassian.net/browse/VUE-592)
While I was attempting to squash and reword the commits on this branch things were getting tangled up due to a few merges of our Main branch into it. When completing the 'git rebase' that I was running in order to squash and reword commits, it attributed a lot of you commits to me and got the history confused.
I figured it was better to start a brand new branch and put my changes in it which is what is this. Many lessons learned in this process. Thank you all for your input along the way with this ticket, I think the final result turned out nice. 
_[old PR]_(https://github.com/kiva/kv-ui-elements/pull/51)
> feat: KvSelect component and storybook story

- kv-components/vue/KvContentfulImg.vue
- kv-components/vue/stories/KvContentfulImg.stories.js
Some differences/enhancements from the component currently used in UI
* Added some more prop validators.
* Split crop prop to fit / focus props. This will allow a more direct mapping of the props to the contentful image api.
>  feat(KvContentfulImg): Component that renders image from contentful

- @kiva/kv-tokens/configs/kivaTypography.js
Convert letter-spacing of h1,h2,h3,h4s to ems so the existing UI letter spacing will look fairly normal.
> VUE-604 letter spacing 

- @kiva/kv-components/vue/KvSelect.vue
Updating the value of KvSelect to accept both numbers and strings.
> fix: KvSelect, updating value to accept number and string

- @kiva/kv-components/vue/KvGrid.vue
- @kiva/kv-components/vue/KvPageContainer.vue
- @kiva/kv-components/vue/stories/KvGrid.stories.js
- @kiva/kv-components/vue/stories/KvPageContainer.stories.js
Two components that can be used separately or together. 
KvPageContainer constrains and centers content per the design spec.
KvGrid is a light wrapper around tailwind's grid class that keeps the column gaps to the design specification.
> VUE-611 Grid and container components

- @kiva/kv-components/vue/KvProgressBar.vue
- @kiva/kv-components/vue/stories/KvProgressBar.stories.js
fix(KvProgressBar): Add ariaLabel prop, fix aria attribute DOM placement, add min prop in case it's non-zero.
perf(KvProgressBar): Animate using css transforms instead of width
> VUE-583 KvProgressBar improvements

- @kiva/kv-components/vue/KvTab.vue
- @kiva/kv-components/vue/KvTabPanel.vue
- @kiva/kv-components/vue/KvTabs.vue
- @kiva/kv-components/vue/stories/KvTabs.stories.js
> feat(KvTabs): Accessible components for implementing a tab UI pattern

- @kiva/kv-components/vue/KvTextLink.vue
- @kiva/kv-components/vue/stories/KvTextLink.stories.js
- @kiva/kv-tokens/configs/kivaTypography.js
- @kiva/kv-tokens/configs/tailwind.config.js
> feat(KvTextLink): A component for a stylized text link with icon option

- @kiva/kv-components/vue/KvToast.vue
- @kiva/kv-components/vue/stories/KvToast.stories.js
- @kiva/kv-tokens/configs/tailwind.config.js
- @kiva/kv-tokens/primitives.json
This should be nearly a drop-in replacement for KvTipMessage, though I'd like to handle watching the $route within TheTipMessage.vue instead.
> VUE-589 KvToast

- @kiva/kv-components/vue/KvLightbox.vue
- @kiva/kv-components/vue/KvSelect.vue
- @kiva/kv-components/vue/KvTab.vue
Fixes for 1, 2, 8 in that ticket
> GROW-751 misc fixes

- @kiva/kv-components/package.json
- @kiva/kv-components/utils/throttle.js
- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/KvCarouselSlide.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
- @kiva/kv-tokens/configs/tailwind.config.js
- package-lock.json
> feat: Adds KvCarousel component

- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
I had to modify this component to work with the use case of the upcoming cause based landing page.
See story: 
https://608b4cf87f686c00213841b1-qpcaijlqvm.chromatic.com/iframe.html?id=kvcarousel--responsive-slides&args=&viewMode=story
For the use case we are trying to solve.
> feat: modify KvCarousel to allow for responsive slides

- @kiva/kv-components/vue/KvButton.vue
- @kiva/kv-components/vue/stories/KvButton.stories.js
Looks the same as the hover state, but doesn't change when hovered. First time it's shown up in a design that I've seen, but maybe more on the way.
> feat: Add active state to KvButton

- @kiva/kv-components/vue/KvCheckbox.vue
- @kiva/kv-components/vue/stories/KvCheckbox.stories.js
> fix(KvCheckbox): Allow checkboxes to use an array in v-model

- @kiva/kv-components/vue/stories/KvThemeProvider.stories.js
- @kiva/kv-tokens/configs/tailwind.config.js
- @kiva/kv-tokens/primitives.json
> Improve border-tertiary visibility in mint theme, add lg (40px) border radius

- @kiva/kv-components/vue/KvTextInput.vue
- @kiva/kv-tokens/configs/kivaTypography.js
- @kiva/kv-tokens/configs/tailwind.config.js
This is part of the broader task of removing Foundation's base styling from UI.
> VUE-736 Add placeholder styling to our base styles

- @kiva/kv-components/vue/KvCheckbox.vue
- @kiva/kv-components/vue/stories/KvCheckbox.stories.js
Similar to https://608b4cf87f686c00213841b1-jzxgtxmnny.chromatic.com/?path=/story/forms-kvtextinput--invalid
> feat(KvCheckbox): add a prop and visual styling to tell a user the input is invalid

- @kiva/kv-components/vue/KvButton.vue
Doing this as an example of using vue-demi to make a component that's compatible with both Vue 2 and Vue 3. Storybook still builds and the tests still pass.
> refactor(@kiva/kv-components): use vue composition api for KvButton

- @kiva/kv-components/vue/KvButton.vue
- @kiva/kv-components/vue/KvSelect.vue
- @kiva/kv-components/vue/KvSwitch.vue
- @kiva/kv-components/vue/KvTextInput.vue
Will need to get these changes into the vue3 branch as well
> misc Safari fixes

- @kiva/kv-components/package.json
- @kiva/kv-components/vue/.storybook/preview.js
Needed to add composition API to storybook config and ensure Vue 2 was being used for this to work properly.
> chore: use Vue 2 & composition api for storybook

- @kiva/kv-components/README.md
- @kiva/kv-tokens/README.md
It seems I need some files changed within the package themselves for Lerna to know which packages need to be bumped
> chore!: tailwind v3 update

- @kiva/kv-components/README.md
- @kiva/kv-tokens/README.md
BREAKING CHANGE: Tailwind dependency is now v3
> feat!: upgrade Tailwind to v3

- @kiva/kv-components/vue/KvButton.vue
- @kiva/kv-components/vue/stories/KvButton.stories.js
- @kiva/kv-tokens/primitives.json
Verified with Nathan. 
Change caution color slightly, and add caution hover variant, as well as story for button.
> feat: add new caution variant to buttons

- @kiva/kv-components/vue/KvLoadingPlaceholder.vue
- @kiva/kv-components/vue/stories/KvLoadingPlaceholder.stories.js
- package-lock.json
https://kiva.atlassian.net/browse/VUE-1220
- Basic placeholder ported from `ui` repo
> Vue 1220 header create shared placeholder component

- @kiva/kv-components/utils/expander.js
- @kiva/kv-components/vue/KvAccordionItem.vue
- @kiva/kv-components/vue/KvExpandable.vue
- @kiva/kv-components/vue/stories/KvAccordionItem.stories.js
Currently what the component looks like in Storybook!
> feat: creating a global reusable component (KvAccordionItem) 

- @kiva/kv-components/vue/KvContentfulImg.vue
- @kiva/kv-components/vue/stories/KvContentfulImg.stories.js
> feat(KvContentfulImg): add optional caption MARS-243

- package-lock.json
Result of running `npm update url-parse minimist follow-redirects moment terser parse-url @actions/core`, based on the open dependabot pull requests.
> chore(deps): security updates for development module dependencies

- @kiva/kv-components/vue/stories/KvThemeProvider.stories.js
- @kiva/kv-tokens/configs/kivaColors.cjs
- @kiva/kv-tokens/primitives.json
New theme to support styles for new homepage experiments.
> feat: add dark mint theme

- @kiva/kv-components/vue/KvContentfulImg.vue
Are there landing pages we can look at to verify these changes work correctly?
> fix(KvContentfulImg): match size and fit of picture to figure wrapper MARS-265

- @kiva/kv-components/vue/KvExpandableQuestion.vue
- Ref itself was being used instead of value
> fix: use value instead of ref

- @kiva/kv-components/vue/KvContentfulImg.vue
Resize leaf icon for design purposes
> style: change leaf caption dimensions

- @kiva/kv-components/vue/KvToast.vue
- @kiva/kv-components/vue/stories/KvToast.stories.js
https://kiva.atlassian.net/browse/CORE-1052
- We wanted a way to show a toast for a specific amount of time
- This allows us to tell a toast to display for exact 10s, for example
> feat: hide delay param for toast

- @kiva/kv-components/tests/unit/specs/components/KvPagination.spec.js
- @kiva/kv-components/vue/KvPagination.vue
- @kiva/kv-components/vue/stories/KvPagination.stories.js
Moving KvPagination component for blog work.
> feat: move KvPagination component to kv-elements

- @kiva/kv-components/vue/stories/StyleguidePrimitives.stories.js
- @kiva/kv-tokens/configs/tailwind.config.cjs
- @kiva/kv-tokens/primitives.json
> feat: add custom blog colors

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLendAmountButton.vue
- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLendAmountButton.stories.js
- While adding the loan card to the homepage, these fixes were required
- Make tag toggleable since homepage needs to external link to `ui` loan pages
- Fixed issue with double CTA
> feat: loan card CTA fixes needed for home page

- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLendCta.stories.js
- There was an issue when a loan had the view loan prop and was funded (view loan button would appear + be disabled)
> feat: handle view loan when funded

- @kiva/kv-components/vue/KvLocationSelector.vue
- @kiva/kv-components/vue/stories/KvLocationSelector.stories.js
- new `KvLocationSelector` component added to `kv-components` package to have a shared countries checkbox list
> Core 1372 filters location selector

- @kiva/kv-tokens/primitives.json
Change facebook color to consolidate it with other apps
> feat: change facebook color definition

- @kiva/kv-components/vue/KvLocationSelector.vue
> Core 1372 filters location selector emit left

- @kiva/kv-shop/.eslintrc.cjs
- @kiva/kv-shop/README.md
- @kiva/kv-shop/package.json
- @kiva/kv-shop/src/basket.ts
- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/components/KvPaymentSelect.vue
- @kiva/kv-shop/src/index.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/shopError.ts
- @kiva/kv-shop/src/subscriptionCheckout.ts
- @kiva/kv-shop/src/useBraintreeDropIn.ts
- @kiva/kv-shop/tsconfig.json
- lerna.json
- package-lock.json
- package.json
A lot of TODOs and several open questions in this, but I wanted to start to get eyes on it.
> feat: add new package kv-shop for payment and checkout logic

- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/subscriptionCheckout.ts
- @kiva/kv-shop/src/useBraintreeDropIn.ts
This fix should come along with transpiling `kv-shop` on your project
> fix: add core portion to gql import to match cps

- @kiva/kv-components/vue/KvLocationSelector.vue
- number of loans added to countries text
> Core 1372 filters location selector number loans

- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/subscriptionCheckout.ts
- @kiva/kv-shop/src/useBraintreeDropIn.ts
Adding optional chaining on error checking
> fix: always throwing error due to reading from undefined

- @kiva/kv-components/vue/KvLocationSelector.vue
- regions watcher removed; not needed b/c region prop is reactive
> fix: regions watcher removed from location selector

- @kiva/kv-shop/src/components/KvPaymentSelect.vue
- @kiva/kv-shop/src/subscriptionCheckout.ts
> fix: graphql mutation error

- @kiva/kv-components/vue/KvLocationSelector.vue
- color changed in KvLocationSelector component
> Core 1372 location selector color changed

- @kiva/kv-loan-filters/src/categories.ts
- @kiva/kv-loan-filters/src/queryParamUtils.ts
- @kiva/kv-loan-filters/src/searchStateUtils.ts
- @kiva/kv-loan-filters/src/tests/categories.spec.ts
- @kiva/kv-loan-filters/src/tests/queryParamUtils.spec.ts
https://kiva.atlassian.net/browse/CORE-1386
- Changes needed for the category filter page
- Currently it's the only page using these utils
> feat: changes to filter utils for category filter page

- @kiva/kv-shop/src/basket.ts
- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/components/KvPaymentSelect.vue
- @kiva/kv-shop/src/shopError.ts
- @kiva/kv-shop/src/tests/basket.spec.ts
- @kiva/kv-shop/src/tests/basketItems.spec.ts
- @kiva/kv-shop/src/tests/shopError.spec.ts
Check invalid basket id error, then create a new basket and save donation amount on cookie to be used on CPS.
> feat: handle invalid basketId on new donation module

- @kiva/kv-loan-filters/src/activities.ts
- @kiva/kv-loan-filters/src/tests/activities.spec.ts
- Team functional testing found that the activity filters weren't being applied in the new category filter page
> feat: activity ID should handle empty array

- @kiva/kv-loan-filters/src/activities.ts
- @kiva/kv-loan-filters/src/tests/activities.spec.ts
- Activity ID wasn't being returned for the loan search state in some situations
> Fix activity search state

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- class added to loan use link to disable clicking when loading
> feat: disabling to click loan use when loading

- @kiva/kv-components/utils/loanUtils.js
- lower default price for lenders coming from repayments email added to loan utility
- requirements here: https://kiva.atlassian.net/browse/CORE-1468
> feat: balance campaign prices added to loan utility

- @kiva/kv-components/vue/KvPagination.vue
- avoid fractional page number in `KvPaginator` component
> feat: avoid fractional page number in kvpaginator component

- @kiva/kv-loan-filters/src/pageOffset.ts
- page number rounded to push it to the route correctly
> fix: page number rounded in pageoffset library

- @kiva/kv-loan-filters/src/filterOptionUtils.ts
> feat: add most recent label

- @kiva/kv-components/tailwind.config.cjs
- @kiva/kv-components/vue/KvToast.vue
- @kiva/kv-components/vue/stories/KvToast.stories.js
- package-lock.json
https://kiva.atlassian.net/browse/CIT-328
- Added TW configs for box shadow
- Added bg variations
- Added flag for adding drop/box shadow
> Toast variations

- @kiva/kv-components/vue/KvToast.vue
- @kiva/kv-components/vue/stories/KvToast.stories.js
https://kiva.atlassian.net/browse/CIT-366
- Rolled back bg and shadow props
- Added default shadow to all toasts (reviewed by design)
> Rollback tooltip props

- @kiva/kv-loan-filters/src/keywordSearch.ts
- @kiva/kv-loan-filters/src/tests/keywordSearch.spec.ts
- FLSS filter for keyword field updated from `description` to `keywordSearch`
> feat: flss filter for keyword field updated

- @kiva/kv-components/vue/KvLoanUse.vue
- I noticed that the loan use statement wasn't suppressing the loan name (borrower name)
> feat: loan name wasn't being suppressed from hotjar

- @kiva/kv-components/vue/KvLoanTag.vue
- Prioritizing matching text in loan tag component
> feat: prioritizing matching text in loan tag component

- .nvmrc
- @kiva/kv-analytics/.eslintrc.cjs
- @kiva/kv-analytics/jest.config.cjs
- @kiva/kv-analytics/package.json
- @kiva/kv-analytics/src/SimpleQueue.ts
- @kiva/kv-analytics/src/index.ts
- @kiva/kv-analytics/src/tests/SimpleQueue.spec.ts
- @kiva/kv-analytics/tsconfig.json
- lerna.json
- package-lock.json
- package.json
I need this for tracking donation transaction in optimizely in kv-shop. Largely just copied from UI. This allows these common tracking functions to be used across kv-ui-elements and in UI/CPS.
> kv-analytics library

- @kiva/kv-shop/package.json
- @kiva/kv-shop/src/index.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/receipt.ts
- @kiva/kv-shop/src/reciept.ts
- package-lock.json
Replicating transaction tracking from UI for one-time checkouts.
> feat: checkout transaction tracking

- @kiva/kv-components/utils/loanCard.js
in refactoring this and fixing some linting errors I created this bug
> fix: p4 tag on loan card

- .github/workflows/run-ui-tests.yml
Should resolve linting errors.
> build: run package build scripts before linting and testing

- @kiva/kv-loan-filters/src/filterUiConfigs.ts
- @kiva/kv-loan-filters/src/filterUtils.ts
- @kiva/kv-loan-filters/src/flexibleFundraisingEnabled.ts
- @kiva/kv-loan-filters/src/tests/fixtures/mockLoanSearchData.ts
- @kiva/kv-loan-filters/src/tests/flexibleFundraisingEnabled.spec.ts
https://kiva.atlassian.net/browse/ACK-867
- Added new filter from `ui` repo to shared filters
- Not currently used but ready for the future
> feat: add new flexibleFundraisingEnabled filter

- @kiva/kv-components/tests/unit/specs/components/KvCommentsAdd.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsContainer.spec.js
- @kiva/kv-components/vue/KvCommentsAdd.vue
- @kiva/kv-components/vue/KvCommentsContainer.vue
- @kiva/kv-components/vue/stories/KvCommentsAdd.stories.js
- @kiva/kv-components/vue/stories/KvCommentsContainer.stories.js
https://kiva.atlassian.net/browse/ACK-924
- Created component for adding a comment to an activity feed
- Added it to the comments container
- Removed the activity ID, since the app using these components will be interacting with the activity
> feat: add comments add component

- @kiva/kv-shop/src/oneTimeCheckout.ts
- valetInviter param added to executeOneTimeCheckout function
> feat: valetinviter param added to executeonetimecheckout

- @kiva/kv-components/tests/fixtures/mockFeedActivityData.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsHeartButton.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsList.spec.js
- @kiva/kv-components/vue/KvButton.vue
- @kiva/kv-components/vue/KvCommentsHeartButton.vue
- @kiva/kv-components/vue/KvCommentsList.vue
- @kiva/kv-components/vue/KvCommentsListItem.vue
- @kiva/kv-components/vue/stories/KvCommentsHeartButton.stories.js
- KvCommentsHeartButton added for comments stuff
> feat: kvcommentsheartbutton added for comments stuff

- @kiva/kv-activity-feed/src/index.ts
- @kiva/kv-activity-feed/src/tests/ActivityFeedService.spec.ts
- Adding `addLikeToComment` and `removeReaction` methods to kv-activity-feed.
> feat: adding like to comment and remove reaction methods added

- @kiva/kv-activity-feed/src/index.ts
- @kiva/kv-activity-feed/src/tests/ActivityFeedService.spec.ts
- add text to child reaction to reply comments
> feat: add text to child reaction to reply comments

- @kiva/kv-components/tests/unit/specs/utils/imageUtils.spec.js
- @kiva/kv-components/utils/imageUtils.js
- @kiva/kv-components/vue/KvUserAvatar.vue
- @kiva/kv-components/vue/stories/KvUserAvatar.stories.js
- This component will be used in the new commenting components
- Ported from CPS and adjusted slightly
> feat: add generic user avatar component

- @kiva/kv-components/tests/unit/specs/components/KvCommentsReplyButton.spec.js
- @kiva/kv-components/vue/KvCommentsListItem.vue
- @kiva/kv-components/vue/KvCommentsReplyButton.vue
- @kiva/kv-components/vue/stories/KvCommentsReplyButton.stories.js
- replies count added to reply commenting button
> feat: replies count added to reply commenting button

- @kiva/kv-components/vue/KvCommentsListItem.vue
> fix: comments count fixed

- @kiva/kv-components/tests/unit/specs/components/KvCommentsAdd.spec.js
- @kiva/kv-components/vue/KvCommentsAdd.vue
- @kiva/kv-components/vue/KvCommentsContainer.vue
- @kiva/kv-components/vue/KvCommentsList.vue
- @kiva/kv-components/vue/KvCommentsListItem.vue
- @kiva/kv-components/vue/KvUserAvatar.vue
- Small differences: slightly smaller avatar from before, fallback seen for visitor (kiva logo)
> feat: use new avatar in commenting components

- @kiva/kv-components/tests/unit/specs/components/KvCommentsList.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsListItem.spec.js
- @kiva/kv-components/vue/KvCommentsListItem.vue
- `fetchLenderInfo` method injected to `KvCommentsListItem` component to fetch comment's author info
> feat: fetchlenderinfo method injected to comment item component

- @kiva/kv-components/vue/KvCommentsListItem.vue
- @kiva/kv-components/vue/KvCommentsReplyButton.vue
- @kiva/kv-components/vue/stories/KvCommentsContainer.stories.js
- @kiva/kv-components/vue/stories/KvCommentsList.stories.js
- @kiva/kv-components/vue/stories/KvCommentsListItem.stories.js
https://kiva.atlassian.net/browse/ACK-1036
- Updated the reply button to match other buttons (hover state mainly)
- Fixed commenting stories that needed the `provide`
- Added comment about providing method
> feat: small commenting fixes

- @kiva/kv-components/vue/KvInlineActivityCard.vue
- @kiva/kv-components/vue/KvInlineActivityFeed.vue
- @kiva/kv-components/vue/stories/KvInlineActivityCard.stories.js
- @kiva/kv-components/vue/stories/KvInlineActivityFeed.stories.js
> feat: inline activity feed components added

- @kiva/kv-components/vue/KvCommentsListItem.vue
https://kiva.atlassian.net/browse/ACK-1076
> fix: fix data reference for comment list item

- @kiva/kv-components/tests/unit/specs/components/KvCommentsContainer.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsList.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsListItem.spec.js
- @kiva/kv-components/vue/KvCommentsContainer.vue
- @kiva/kv-components/vue/KvCommentsListItem.vue
- logged in user feats for commenting components
> feat: logged in feats for commenting components

- @kiva/kv-components/vue/KvCommentsListItem.vue
> fix: allow heart on last comment level

- @kiva/kv-activity-feed/src/tests/parseError.spec.ts
- @kiva/kv-activity-feed/src/utils/parseError.ts
- @kiva/kv-components/vue/KvCommentsListItem.vue
- Turns out stream simply doesn't support reactions at this level 🤦 
- I sometimes see errors locally about the error import, so I made the import more specific
> fix: revert level 3 reactions and more specific error src

- @kiva/kv-components/tests/fixtures/mockFeedActivityData.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsListItem.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsReplyButton.spec.js
- @kiva/kv-components/vue/KvCommentsListItem.vue
- @kiva/kv-components/vue/KvCommentsReplyButton.vue
- collapsable replies list added to commenting component
> feat: collapsable replies list added to commenting component

- @kiva/kv-components/tests/fixtures/mockFeedActivityData.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsList.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvCommentsListItem.spec.js
- @kiva/kv-components/vue/KvCommentsContainer.vue
- @kiva/kv-components/vue/KvCommentsList.vue
- @kiva/kv-components/vue/KvCommentsListItem.vue
- @kiva/kv-components/vue/stories/KvCommentsContainer.stories.js
- @kiva/kv-components/vue/stories/KvCommentsList.stories.js
- @kiva/kv-components/vue/stories/KvCommentsListItem.stories.js
- Starting to adjust components for new data from chat product (rather than activity feed product)
- This is just the first step, so I can start seeing the data format returned for replies
- More to come soon (stories currently broken)
> fix: adjust commenting initially for chat

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- loan card bug fixed
bug:
fix:
> fix: loan card bug fixed

- @kiva/kv-components/vue/KvInlineActivityCard.vue
- @kiva/kv-components/vue/stories/KvInlineActivityCard.stories.js
- @kiva/kv-components/vue/stories/KvInlineActivityFeed.stories.js
- inline activity feed amount lent updated
> feat: inline activity feed amount lent updated

- @kiva/kv-activity-feed/package.json
- @kiva/kv-activity-feed/src/index.ts
- @kiva/kv-activity-feed/src/tests/ActivityFeedService.spec.ts
- @kiva/kv-components/vue/KvCommentsListItem.vue
- package-lock.json
- Changed `ActivityFeedService` to work for stream chat product
- Small fix to comment component
> feat: activity feed chat changes

- @kiva/kv-activity-feed/src/index.ts
- @kiva/kv-activity-feed/src/tests/ActivityFeedService.spec.ts
- Listen to all events and send latest messages to callback
> feat: chat product websockets

- @kiva/kv-components/tests/unit/specs/components/KvClassicLoanCard.spec.js
- @kiva/kv-components/vue/KvActivityRow.vue
- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLoanActivities.vue
- @kiva/kv-components/vue/stories/KvActivityRow.stories.js
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLoanActivities.stories.js
- Activity feed components added
- Activity feed added to loan card
> feat: activity feed added to loan card

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- passing error message to loan card and activity feed
> feat: pass error message to loan card and activity feed

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/KvLoanActivities.vue
- @kiva/kv-components/vue/KvWideLoanCard.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLendCta.stories.js
- @kiva/kv-components/vue/stories/KvWideLoanCard.stories.js
- Huge lent amount, >$500, added to LendCta dropdown
- Options added to dropdown in $100 increments up to $1000 for the case
- Change only affects logged in users
- Experiment flag added to enable this feat
- Option added If amount left is not a $100 increment to complete loan
> feat: huge lent amount added to lend cta dropdown

- @kiva/kv-components/vue/KvVotingCard.vue
change icon to leaf in vote card
> feat: change voting card icon

- @kiva/kv-components/tests/unit/specs/utils/loanUtils.spec.js
- @kiva/kv-components/utils/loanUtils.js
- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/stories/KvLendCta.stories.js
https://kiva.atlassian.net/browse/MP-88
- Extended existing "huge amount" experiment/feature with options from $1000 -> $10000
- Extracted previously implemented methods and placed under test
> feat: add 1 k increments up to 10 k

- @kiva/kv-tokens/configs/kivaTypography.cjs
This should help with super tight h2 multiline layours and hopefully cut off descenders as well.
> fix: increate h2 line height

- @kiva/kv-components/tests/unit/specs/components/KvClassicLoanCard.spec.js
- @kiva/kv-components/utils/loanCard.js
- @kiva/kv-components/vue/KvLoanCallouts.vue
- @kiva/kv-components/vue/stories/KvLoanCallouts.stories.js
> fix: activity removed from clickable tags

- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
- start index tweaks added to kvcarousel component
> feat: start index added to kvcarousel component

- @kiva/kv-shop/src/basketCredits.ts
- @kiva/kv-shop/src/managedAccount.ts
- @kiva/kv-shop/src/tests/basketCredits.spec.ts
- @kiva/kv-shop/src/tests/managedAccount.spec.ts
- Mutations for adding and removing credit by type which will accomodate upc and promo code work
- Query for `promoCampaign` for fetching any promo data associated with the basket or a managed account
> Feat shop promo queries

- @kiva/kv-shop/src/basketCredits.ts
- @kiva/kv-shop/src/index.ts
- @kiva/kv-shop/src/managedAccount.ts
- @kiva/kv-shop/src/tests/basketCredits.spec.ts
- @kiva/kv-shop/src/tests/managedAccount.spec.ts
- Export the new managedAccount module
- Add options object for passing variables and fetchPolicy to new promo mutations and promo campaign query
- Added guards for missing required variables and additional tests
> fix: export managedAccount module

- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
- Aside controls variant added to carousel component
> feat: aside controls variant added to carousel component

- @kiva/kv-components/vue/KvCarousel.vue
- carousel controls arrow added for aside controls version
> feat: carousel controls arrow added for aside version

- @kiva/kv-tokens/configs/kivaColors.cjs
- @kiva/kv-tokens/primitives.json
> feat: brown theme added to tokens

- @kiva/kv-components/vue/stories/KvThemeProvider.stories.js
- package-lock.json
- Dark Stone theme provider added
> feat: dark stone theme provider added

- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
- dotted version for carousel controls
> feat: dotted version for carousel controls

- @kiva/kv-components/utils/mapUtils.js
- @kiva/kv-components/vue/KvMap.vue
- Working on the Vue migration encountered an issue with Vite and importing json in the util file
- I tested this locally in the `node_modules` folder manually and it seems to work fine
> fix: vite has some complications around importing json

- @kiva/kv-components/package.json
- @kiva/kv-components/utils/Alea.js
- @kiva/kv-components/utils/touchEvents.js
- @kiva/kv-components/vue/KvPieChart.vue
- @kiva/kv-components/vue/KvPopper.vue
- @kiva/kv-components/vue/KvTooltip.vue
- @kiva/kv-components/vue/KvTreeMapChart.vue
- @kiva/kv-components/vue/stories/KvPieChart.stories.js
- @kiva/kv-components/vue/stories/KvTooltip.stories.js
- @kiva/kv-components/vue/stories/KvTreeMapChart.stories.js
- package-lock.json
- charts added to library
Pie chart:
Map Tree chart:
> feat: charts added to library

- @kiva/kv-components/utils/loanCard.js
- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
- @kiva/kv-components/vue/KvLoanTag.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvIntroductionLoanCard.stories.js
https://kiva.atlassian.net/browse/MP-726
- Many different tweaks to the new loan card that will be used on the home page
- Below are a few versions
> feat: introduction loan cards styling updates

- @kiva/kv-components/utils/loanCard.js
- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
https://kiva.atlassian.net/browse/MP-726
- Fixed prop usage from previous PR (I accidentally removed reactivity)
> fix: props usage removed reactivity

- @kiva/kv-components/vue/KvMap.vue
- async countries border data import added
> feat: async countries border data import

- @kiva/kv-components/vue/KvPieChart.vue
- emitted event added to pie chart component
> feat: emitted event added to pie chart component

- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
- @kiva/kv-components/vue/stories/KvIntroductionLoanCard.stories.js
https://kiva.atlassian.net/browse/MP-745
- Added bookmark functionality for new loan card
> feat: add bookmark functionality to new loan card

- @kiva/kv-components/vue/KvSideSheet.vue
- @kiva/kv-components/vue/stories/KvSideSheet.stories.js
- desktop side sheet component added to library
> feat: desktop side sheet component added to library

- @kiva/kv-components/package.json
- @kiva/kv-components/tests/unit/specs/utils/treemap.spec.js
- @kiva/kv-components/utils/treemap.js
- @kiva/kv-components/vue/KvTreeMapChart.vue
- package-lock.json
- There was an issue with the export in the forked repo
- The code was MIT licensed and minimal, so I moved it over to kiva repo -> quicker than tracking down the issue with the forked repo
> feat: move treemap into repo

- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
- Found an element (name) not clickable on the new loan cards during QA
> fix: add missing click name

- @kiva/kv-components/vue/KvLightbox.vue
https://kiva.atlassian.net/browse/MP-780
- Hoping this fixes the memory leak
> fix: remove computed from next tick

- @kiva/kv-components/vue/KvPieChart.vue
- @kiva/kv-components/vue/stories/KvPieChart.stories.js
> fix: pie chart not visible with only one value MP-791

- @kiva/kv-components/vue/KvVotingCardV2.vue
- @kiva/kv-components/vue/stories/KvVotingCardV2.stories.js
New voting card component with story
> feat: new voting card

- @kiva/kv-components/vue/KvVotingCardV2.vue
- @kiva/kv-components/vue/stories/KvVotingCardV2.stories.js
padding: 35% was a bad idea and it was making the cards difficult to align inside a grid.
> feat: vertically align contents inside voting cards 2 to bottom

- @kiva/kv-components/vue/KvMap.vue
Adds note about data sources for the global map version of the component
> chore: add comment with data sources

- @kiva/kv-components/utils/carousels.js
- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/KvVerticalCarousel.vue
- @kiva/kv-components/vue/stories/KvVerticalCarousel.stories.js
* implement basic vertical carousel, we can add features later if needed
* add stories for carousel
* move shared carousel code to util file.
> feat: basic vertical carousel

- @kiva/kv-components/package.json
- @kiva/kv-components/vue/stories/KvMaterialIcon.stories.js
- package-lock.json
> chore: mdijs package updated

- @kiva/kv-components/vue/KvSideSheet.vue
This should resolve an issue I encountered with the side sheet when changing browser size (mobile -> desktop)
> fix: resolve issue when screen size is changed and opening behavior changes

- @kiva/kv-components/vue/KvSideSheet.vue
https://kiva.atlassian.net/browse/MP-1211
> fix: side sheet shouldn't be full height

- @kiva/kv-components/src/vue/KvSideSheet.vue
- esc key event added to side sheet component
> feat: esc key event added to side sheet component

- @kiva/kv-components/src/vue/KvLendCta.vue
- package-lock.json
Making the lend CTA selected state a bit more clear.
> fix: change border color on button for lend cta

- @kiva/kv-components/src/vue/KvCartModal.vue
- @kiva/kv-components/src/vue/stories/KvCartModal.stories.js
- ATB modal kept open if mouse is over
> feat: atb modal kept open if mouse is over

- @kiva/kv-components/src/vue/KvCartPill.vue
- @kiva/kv-components/src/vue/KvLendCta.vue
- @kiva/kv-components/src/vue/stories/KvLendCta.stories.js
- Cart pill added to lend CTA component
> feat: pill added to lend cta

- @kiva/kv-components/src/vue/KvCartModal.vue
- @kiva/kv-components/src/vue/stories/KvCartModal.stories.js
- cart modal category option added
> feat: cart modal category option added

- @kiva/kv-components/src/vue/KvUserAvatar.vue
- loader added to KvUserAvatar component as image is loaded
https://kiva.atlassian.net/browse/MP-1444
> feat: loader added to kv user avatar component

- @kiva/kv-components/src/vue/KvUserAvatar.vue
https://kiva.atlassian.net/browse/MP-1471
> fix: error was being thrown safely on prod

- @kiva/kv-components/src/vue/KvUserAvatar.vue
https://kiva.atlassian.net/browse/MP-1511
> fix: resolve when avatar image disappears

- @kiva/kv-components/src/vue/KvVerticalCarousel.vue
Center the up/down buttons on mobile for the vertical carousel
> feat: center buttons on vertical carousel

- @kiva/kv-loan-filters/src/loanChannelQueryMap.ts
- categories added to loan channel map file
> feat: categories added to loan channel map file

- @kiva/kv-components/src/vue/KvLendCta.vue
- @kiva/kv-components/src/vue/stories/KvLendCta.stories.js
We want to go back to showing "Lend $25" when max amount is 25 and loan has more than 25 left unreserved
> feat: use stranded lend button when max amount is 25

- @kiva/kv-loan-filters/src/activities.ts
- @kiva/kv-loan-filters/src/categories.ts
- @kiva/kv-loan-filters/src/city.ts
- @kiva/kv-loan-filters/src/dafEligible.ts
- @kiva/kv-loan-filters/src/daysUntilExpiration.ts
- @kiva/kv-loan-filters/src/distributionModels.ts
- @kiva/kv-loan-filters/src/flexibleFundraisingEnabled.ts
- @kiva/kv-loan-filters/src/genders.ts
- @kiva/kv-loan-filters/src/isIndividual.ts
- @kiva/kv-loan-filters/src/isMatchable.ts
- @kiva/kv-loan-filters/src/keywordSearch.ts
- @kiva/kv-loan-filters/src/lenderRepaymentTerms.ts
- @kiva/kv-loan-filters/src/loanAmount.ts
- @kiva/kv-loan-filters/src/pageLimit.ts
- @kiva/kv-loan-filters/src/pageOffset.ts
- @kiva/kv-loan-filters/src/partnerAvgProfitability.ts
- @kiva/kv-loan-filters/src/partnerDefaultRate.ts
- @kiva/kv-loan-filters/src/partnerRiskRating.ts
- @kiva/kv-loan-filters/src/partners.ts
- @kiva/kv-loan-filters/src/postalCode.ts
- @kiva/kv-loan-filters/src/regions.ts
- @kiva/kv-loan-filters/src/sectors.ts
- @kiva/kv-loan-filters/src/sortOptions.ts
- @kiva/kv-loan-filters/src/state.ts
- @kiva/kv-loan-filters/src/tags.ts
- @kiva/kv-loan-filters/src/themes.ts
- @kiva/kv-loan-filters/src/trusteeId.ts
https://kiva.atlassian.net/browse/MP-1593
- Need state key for dynamic filtering hiding in combo page
- Found simpler solution for previous top/bottom border configs
> fix: adjustments to filter modules for ui implementation

- @kiva/kv-loan-filters/src/loanAmount.ts
https://kiva.atlassian.net/browse/MP-1668
> fix: add config for filter by query for loan amount

- @kiva/kv-loan-filters/src/amountLeft.ts
- @kiva/kv-loan-filters/src/filterUtils.ts
- @kiva/kv-loan-filters/src/tests/amountLeft.spec.ts
https://kiva.atlassian.net/browse/MP-1668
- We actually need `amountLeft`, I accidentally updated the wrong filter in the last PR
> feat: add amount left filter

- @kiva/kv-loan-filters/src/loanChannelQueryMap.ts
https://kiva.atlassian.net/browse/MP-1668
- New channel for almost funded with amount left >= $100
> fix: add new loan channel

- @kiva/kv-components/src/vue/KvLendCta.vue
https://kiva.atlassian.net/browse/MP-1676
> fix: prevent word wrap in lend CTA button

- @kiva/kv-components/src/utils/loanUtils.js
- @kiva/kv-components/src/vue/KvAtbModal.vue
- @kiva/kv-components/src/vue/KvClassicLoanCard.vue
- @kiva/kv-components/src/vue/KvLendCta.vue
- @kiva/kv-components/src/vue/KvLoanActivities.vue
- @kiva/kv-components/src/vue/KvWideLoanCard.vue
- @kiva/kv-components/src/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/src/vue/stories/KvLendCta.stories.js
- @kiva/kv-components/src/vue/stories/KvWideLoanCard.stories.js
- @kiva/kv-components/tests/unit/specs/utils/loanUtils.spec.js
- huge amount flags removed enabling as a feature
> feat: remove huge amount flags

- @kiva/kv-components/src/utils/loanCard.js
- @kiva/kv-components/src/vue/KvClassicLoanCard.vue
- @kiva/kv-components/src/vue/KvWideLoanCard.vue
- @kiva/kv-components/src/vue/stories/KvClassicLoanCard.stories.js
- custom href added to loan card
- https://kiva.atlassian.net/browse/MP-1710
> feat: custom href added to loan card

- @kiva/kv-components/src/vue/KvSideSheet.vue
Move `OnUnmounted` operations outside to its own lifecycle component hook.
> fix: mp-1720 / Fix onUnmounted lifecycle warning in KvSideSheet component

- @kiva/kv-components/src/vue/KvSideSheet.vue
Changing go to link on side sheet for `mdiExportVariant` to `mdiOpenInNew`
https://kiva.atlassian.net/browse/MP-1847
> feat: [MP-1847] - minor change | changing GoToLink icon on side sheet

- @kiva/kv-shop/src/givingFunds.ts
- @kiva/kv-shop/src/index.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
* adds new function for combined flow of validate checkout > create giving fund > donate
> feat: onetime checkout and create giving fund function

- @kiva/kv-components/src/vue/KvCheckbox.vue
Some missing format details for round checkbox
> feat: add animation support to round variant of kvcheckbox

- @kiva/kv-shop/src/oneTimeCheckout.ts
* add a boolean param to `executeOneTimeCheckoutForGivingFund` if it is false, after adding to basket, apply the remove kiva credit mutation
> feat: support kiva credit for add giving fund mutation

- @kiva/kv-tokens/configs/kivaTypography.js
- letter spacing updated for h3
- https://kiva.atlassian.net/browse/MP-1899
> feat: letter spacing updated for h3

- @kiva/kv-components/src/vue/KvLendCta.vue
fixed some issues and refectored a bit isolated a bit more the presets code so that it woundt mess with existing variants
> fix: lend cta issue with mobile viewport

- @kiva/kv-components/src/vue/KvWwwHeader.vue
- @kiva/kv-components/src/vue/KvWwwHeader/KvHeaderMobileMenu.vue
- @kiva/kv-components/src/vue/KvWwwHeader/KvHeaderTakeActionMenu.vue
https://kiva.atlassian.net/browse/MP-2022
https://kiva.atlassian.net/browse/MP-2023
> fix: copy and padding adjustments for new nav

- @kiva/kv-components/src/vue/KvWwwHeader/KvHeaderLinkBar.vue
- @kiva/kv-components/src/vue/KvWwwHeader/KvHeaderMobileMenu.vue
- @kiva/kv-components/src/vue/KvWwwHeader/KvHeaderMyKivaMenu.vue
https://kiva.atlassian.net/browse/MP-2030
https://kiva.atlassian.net/browse/MP-2032
https://kiva.atlassian.net/browse/MP-2029
https://kiva.atlassian.net/browse/MP-2035
Resolved a number of new nav issues. The issue with the nav immediately closing was hard to repro, but I think the adjustments I made fixed it locally, I just can't get it to happen again with the original code at the moment.
> fix: new nav issues resolve mostly in mobile
