- .npmrc
- package.json
This isn't exactly working as advertised for me. But better than nothing. It warns accordingly for an older version of node, but doesnt seem to warn for node 15.3 vs 15.13 but maybe people will get the hint to check here if something isn't working
> Added npm engine and engine-stict option to package.json

- kv-components/package.json
- kv-components/vue/KvMaterialIcon.vue
- kv-components/vue/stories/KvMaterialIcon.stories.js
- package-lock.json
This version imports SVG path data from a material icons library. You pass then pass the path data as a prop to KvMaterialIcon component which renders the SVG.
This is in contrast to #40 which imports SFC Vue Components.
The way you set color and size is the same (tailwind classes).
> VUE-591: KvMaterialIcon, alternate version

- .github/workflows/npm-release.yml
The "Automation" token from npm that is valid for publishing is not valid for the method that Lerna uses to check npm access (see https://github.com/lerna/lerna/issues/2788 for more details about this error). The recommended workaround is using the "--no-verify-access" flag for Lerna. If there is some problem with the authentication, the npm release process will 404, so it will effectively work the same. Additionally, the release job has an earlier step to verify npm access before even installing dependencies, so that should catch any problems with the npm authentication before Lerna is run.
> fix(build): Rename release job and skip npm access verification in lerna

- @kiva/kv-components/package.json
- @kiva/kv-components/tailwind.config.js
- @kiva/kv-components/utils/themeUtils.js
- @kiva/kv-components/vue/stories/Styleguide.stories.js
- @kiva/kv-tokens/configs/tailwind.config.js
- package-lock.json
I've been running into some issues matching designs when arbitrary widths are used (like 550px) inside of a media query. Since it's inside a media query, inline styles can't be used to fudge it.
Since v2.1 Tailwind introduced JIT mode which among other things,
> Generate arbitrary styles without writing custom CSS. Ever needed some ultra-specific value that wasn’t part of your design system, like top: -113px for a quirky background image? Since styles are generated on demand, you can just generate a utility for this as needed using square bracket notation like top-[-113px]. Works with variants too, like md:top-[-113px].
https://tailwindcss.com/docs/just-in-time-mode
The other thing I like a lot is the purge settings are the same in dev or prod mode. So if something's broken in dev because …
> Update Tailwind, use JIT

- @kiva/kv-components/vue/KvLightbox.vue
- @kiva/kv-components/vue/stories/KvLightbox.stories.js
* Fixes lightboxes being cut off on mobile devices, also fixes alert described by error and very small lightboxes not being full width on mobile
GD-120
VUE-700
This article shows the issue we are having:
https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/
See VUE-700 
To reproduce bug, you have to use storybook story view, and it has to be on a native mobile device, the Chrome mobile emulation will not reproduce it. 
It is reproducible both in iOSSimulator and using remote debugging on my Pixel 5
> fix: Fix lightboxes being cut off vertically on mobile

- @kiva/kv-components/vue/KvCheckbox.vue
- @kiva/kv-components/vue/KvRadio.vue
- @kiva/kv-components/vue/KvSwitch.vue
Running into issues on UI with mismatched uuids. This issue does not present itself in storybook. I believe this is caused by SSR setting the UUID on created, then client-side hydration overwriting part of it(?) on mount.
Setting in mounted keeps the IDs in sync.
VUE-714
> KvCheckbox, KvRadio, KvSwitch: Avoid SSR problems when setting the UUID

- package.json
Changes the default commit message from "Publish" so the linter passes on CI releases.
> fix: use conventional commit with lerna for CI

- @kiva/kv-components/vue/KvLightbox.vue
Useful when you have an alert that's just a lightbox title + 2 buttons
> fix(KvLightbox): allow for an empty lightbox body

- @kiva/kv-tokens/configs/tailwind.config.js
Allows you to do
```
<ul class="tw-font-medium">
<li><button>text</button></li>
<li><button>text</button></li>
<li><button>text</button></li>
<li><button>text</button></li>
</ul>
```
instead of 
```
<ul>
<li><button class="tw-font-medium">text</button></li>
<li><button class="tw-font-medium">text</button></li>
<li><button class="tw-font-medium">text</button></li>
<li><button class="tw-font-medium">text</button></li>
</ul>
> fix: allow buttons to inherit font weights

- @kiva/kv-components/package.json
- @kiva/kv-components/vue/.storybook/main.js
- @kiva/kv-components/vue/KvLightbox.vue
- package-lock.json
Adds vueuse package for focus lock. Couldn't get the new version of vue-package-lock to work 🤷 
Fixes a few other things lost in the conversion. If time, some tests around these things would be better.
> VUE3 misc KvLightbox fixes

- @kiva/kv-components/tests/unit/specs/components/KvButton.spec.js
- @kiva/kv-components/vue/KvButton.vue
The `.native` modifier [has been removed in Vue 3](https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed.html). Because KvButton declares that it will emit the `click` event, the click event handlers will not be applied to the button element. This means that KvButton must always emit the native click event when a click happens so that parent components can have access to the native event.
> fix(KvButton): pass through click event for parent

- @kiva/kv-components/tests/unit/specs/components/KvProgressBar.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvTabPanel.spec.js
- @kiva/kv-components/tests/unit/specs/components/KvTabs.spec.js
- @kiva/kv-components/vue/KvTabs.vue
I was able to see and access the `handleKeyDown` method from vue2 on the ref so taking the same approach with these.
I've been trying to find a way to test refs properly/successfully but haven't thus far.
> fix: return additional items for access as refs in vue2

- @kiva/kv-components/vue/KvCarousel.vue
This pr aims to hide carousel controls when there is only 1 page to display.
> refactor: use slideIndicator to hide carousel controls 

- @kiva/kv-components/vue/KvTextInput.vue
- Without this exposed ref, the same ref in the exposed methods appears to not be reactive
- Tested and verified locally in CPS using code in `node_modules`
> fix: ensure ref is defined in exported methods

- @kiva/kv-components/vue/KvCarousel.vue
Noticed this while working on the story card carousel. This bug causes the next slide to be marked as current, instead of the current slide.
> fix(KvCarousel): incorrect slide marked as current

- @kiva/kv-components/vue/KvCarousel.vue
Resizing the window when there is an invisible KvCarousel in the page currently causes the javascript to hang and the page to crash. The cause of the issue appears to be that slidesToScroll is set to 0 (the number of visible slides) when the carousel is reinitialized. Setting it as 'auto' instead in those cases made the issue go away in testing.
> fix(KvCarousel): slidesToScroll should not be 0 MARS-248

- @kiva/kv-tokens/configs/tailwind.config.cjs
Adding these border widths back, not sure why they were disabled in the first place. This enables us to use `tw-border-4` and `tw-border-8`
> feat: add additional border widths

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLendCta.stories.js
- @kiva/kv-loan-filters/src/themes.ts
- package-lock.json
https://kiva.atlassian.net/browse/CORE-1212
- Added "view loan" CTA to new loan cards
- This will be used in the home page
- Included removing earth day theme (campaign is over)
- Included missing package-lock change from last PR
> Core 1212 add view loan cta to new loan cards

- @kiva/kv-components/vue/KvLoanTag.vue
- Turns out the vue countdown component we're using encounters an error in Vue 3 (we have 600+ errors in Sentry since release yesterday)
- Turning off countdown (checked with product) and creating a ticket for sometime in the next few weeks to fix
- Loan tag still appears but just says "Ending soon"
> feat: remove countdown for now from loan tags

- @kiva/kv-shop/src/basket.ts
Current method was returning always undefined due to an extra slash (`/`) in regex
> fix: regex to get cookie by name

- @kiva/kv-components/tests/unit/specs/utils/loanUtils.spec.js
- @kiva/kv-components/utils/loanUtils.js
- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLendAmountButton.vue
- @kiva/kv-components/vue/KvLendCta.vue
https://kiva.atlassian.net/browse/CORE-1426
- Ported loan card CTA changes to shared component for handling ERL campaign changes
- It's an active experiment, and we hope to release the new page experiment next week
- Resolved error around missing prop in `KvLendAmountButton.vue`
> feat: add support for $5 notes default lend CTA dropdown selected amount changing for ERL

- @kiva/kv-components/vue/KvLendCta.vue
- The new loan card dropdown was doubling the click event
- Not a good way to test this locally, but hopefully this solves it
> feat: lend amount CTA double event stop

- .github/workflows/chromatic.yml
Attempting to exclude dependabot prs from running chromatic tasks:
ref. https://github.com/orgs/community/discussions/26079 + https://github.com/GCTC-NTGC/gc-digital-talent/pull/2677/files + https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
> Exclude dependabot prs

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- removing smallest image size option to avoid image bug in tiny screens and zoomed out desktop version
Fixed example
> feat: avoid image bug for tiny screens

- @kiva/kv-components/utils/loanUtils.js
- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLendCta.stories.js
- 5 dollars pre-select dropdown option added to loan cards components
> feat: 5 dollars pre select added to loan card components

- @kiva/kv-components/vue/KvKivaPartnerHeader.vue
https://kiva.atlassian.net/browse/CIT-229
- The `auth0` repo didn't like these (mainly the empty `setup`)
> feat: cleanup unneeded code in kiva partner header

- @kiva/kv-tokens/configs/tailwind.config.cjs
- Used the default TW shadow for the default
- Added the shadow we used for Kiva cards as the `md` variation, since it's a fairly wide shadow
default:
`md`:
> feat: add box shadows to tokens

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- Avoid adding a theme to callouts when equal to category page name in loan card
> feat: avoid adding themes to callouts when equal to category page

- @kiva/kv-shop/.eslintrc.cjs
- @kiva/kv-shop/src/basket.ts
- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/shopError.ts
- @kiva/kv-shop/src/tests/basket.spec.ts
- @kiva/kv-shop/src/tests/basketItems.spec.ts
- @kiva/kv-shop/src/tests/shopError.spec.ts
The invalid basket errors were still coming through snowplow and were presumably displayed to the user before the page was refreshed. This switches to retrying the set tip donation mutation without refreshing the page, up to 2 times.
> fix: retry setting tip donation after creating new basket MARS-429

- @kiva/kv-tokens/configs/tailwind.config.cjs
- In the mindset of simply creating a new default tip message, here's a slightly larger default box shadow that helps distinguish the tip from the same colored background
- This new default is just slightly larger and lighter, and actually aligns better with our existing box shadows
> feat: slightly larger default box shadow

- @kiva/kv-components/tests/unit/specs/components/KvLineGraph.spec.js
- @kiva/kv-components/vue/KvLineGraph.vue
- @kiva/kv-components/vue/stories/KvLineGraph.stories.js
https://kiva.atlassian.net/browse/CIT-334
- Created line graph component using the stash from @emuvente as the base
- Added support for labels (value and x-axis)
- Added ability to just pass in an array of values w/ labels
- Labels will likely get cut-off (or overflow really) in many cases, but this is a good first pass for the impact dashboard
- Line isn't perfect (gets thinner with larger slope, but again, okay for first pass)
- Added some basic tests
> Cit 334 line graph

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvLoanTag.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
- @kiva/kv-components/vue/stories/KvLoanTag.stories.js
- Increasing impact visibility for LSE loans with next features:
1. Add a loan tag for LSE loans that says “High community impact”  
2. Change priority of grey “pills” so that we only show one public tag.
Priority order: 1.Tag, 2. Category, 3. Activity, 4. Sector, 5. Theme
- For now we’ll use the lending partner containing “N/A” as the signifier for these loans
> feat: increase impact visibility for lse loans

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- Bookmark icon position fixed in new loan card to avoid using z-index property preventing to overlap other elements in the page
> fix: bookmark icon position fixed to avoid using z index property

- @kiva/kv-components/vue/KvLoanUse.vue
- @kiva/kv-components/vue/stories/KvLoanUse.stories.js
- Added option why special string to loan use so we can re-use the component in impact dashboard
> Extend loan use with why special

- @kiva/kv-shop/src/basket.ts
- @kiva/kv-shop/src/basketCredits.ts
- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/basketTotals.ts
- @kiva/kv-shop/src/basketVerification.ts
- @kiva/kv-shop/src/checkoutStatus.ts
- @kiva/kv-shop/src/components/KvPaymentSelect.vue
- @kiva/kv-shop/src/index.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/shopError.ts
- @kiva/kv-shop/src/shopQueries.ts
- @kiva/kv-shop/src/tests/basket.spec.ts
- @kiva/kv-shop/src/tests/basketCredits.spec.ts
- @kiva/kv-shop/src/tests/basketItems.spec.ts
- @kiva/kv-shop/src/tests/basketVerification.spec.ts
- @kiva/kv-shop/src/tests/checkoutStatus.spec.ts
- @kiva/kv-shop/src/tests/util/cookie.spec.ts
- @kiva/kv-shop/src/tests/util/poll.spec.ts
- @kiva/kv-shop/src/useBraintreeDropIn.ts
- @kiva/kv-shop/src/util/cookie.ts
- @kiva/kv-shop/src/util/poll.ts
- @kiva/kv-shop/src/util/visitorId.ts
- @kiva/kv-shop/src/validatePreCheckout.ts
One-time async checkout, with some basket state and validation functions. Still needs to actually be tried out with an app, more tests, and a solution for tracking.
Despite the roughness, the basic flow should be all set here. Please let me know if anything looks off with the flow as it is now or if there are any missing pieces not already called out with a TODO!
> feat: one-time checkout and supporting functions MARS-546

- @kiva/kv-components/tests/unit/specs/utils/mapAnimationUtils.spec.js
- @kiva/kv-components/utils/mapAnimation.js
- @kiva/kv-components/vue/KvMap.vue
- @kiva/kv-components/vue/stories/KvMap.stories.js
Opinionated map animation. 
Give an array of borrower points with an image and a coordinate for each. This map will, fly to first borrower, animate lines converging on that point, then fly to the other borrowers in succession. Drawing markers for each borrower on the map. 
This will go on the team challenge (deserving dozen) mvp challenge completion page
Example: 
https://kivahq.slack.com/files/UP32WJ3Q9/F0667J5DRPF/nov-17-2023_11-49-19.mp4
> feat: map mega animation

- @kiva/kv-shop/src/components/KvPaymentSelect.vue
Ran into errors of errorToast being undefined. To fix, I switched to emitting the error message so that consuming apps can display the error (or not) in whatever way they want.
> feat(KvPaymentSelect): emit error instead of using broken local toast

- @kiva/kv-shop/src/oneTimeCheckout.ts
Encountered a 500 when trying to get receipt totals, which then prevented the redirect to thanks. No need to hold things up due to tracking errors, so this just spits them out to the console for now.
> fix: catch errors that may occur during transaction tracking data fetch

- @kiva/kv-components/vue/KvLightbox.vue
- @kiva/kv-components/vue/stories/KvLightbox.stories.js
The focus trap was preventing closing tip message toasts and preventing clicking outside the lightbox to close it.
Using the `allowOutsideClick: true` option allows clicking outside the focus trap, which then allows closing toasts and accessing elements added by browser extensions like password managers.
Including the `'[role="alert"]'` selector string in the focus trap array will include any open alerts in the focus trap, allowing for focusing on the alert close button using tab.
> fix(KvLightbox): allow focus on open alerts, clicks on browser extensions and outside lightbox

- @kiva/kv-shop/.eslintrc.cjs
- @kiva/kv-shop/src/checkoutStatus.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/receipt.ts
- @kiva/kv-shop/src/util/redirect.ts
- @kiva/kv-shop/src/util/visitorId.ts
- @kiva/kv-shop/src/validatePreCheckout.ts
Helps avoid an awkward experience of the checkout buttons appearing to complete moments before a new page loads.
> feat(oneTimeCheckout): redirect in promise so loading state remains active

- @kiva/kv-components/tests/unit/specs/components/KvCommentsContainer.spec.js
- @kiva/kv-components/vue/KvCommentsContainer.vue
- @kiva/kv-components/vue/stories/KvCommentsContainer.stories.js
https://kiva.atlassian.net/browse/ACK-919
- Created basic comments container for the commenting work
- The comments will likely exist in both UI and CPS
- Added basic stories and unit tests
> feat: add basic comments container for future comment work

- @kiva/kv-activity-feed/src/index.ts
- @kiva/kv-activity-feed/src/tests/ActivityFeedService.spec.ts
https://kiva.atlassian.net/browse/ACK-1023
- Add method to `ActivityFeedService` to get or create user
- This should allow us to add the `publicLenderId` to the data stored in stream based on the Kiva user ID
> feat: add activity feed method to get or create user

- @kiva/kv-activity-feed/src/index.ts
- @kiva/kv-activity-feed/src/tests/ActivityFeedService.spec.ts
https://kiva.atlassian.net/browse/ACK-1023
- Apparently `getOrCreate` doesn't update if data is provided
- We need this `updateUser` method to be able to update existing users
> feat: add activity feed update user method

- @kiva/kv-components/package.json
- @kiva/kv-shop/package.json
- package-lock.json
Ran into an error trying to use `@kiva/kv-components` in a vue 2.7 project, and it turns out that's because support for vue 2.7 wasn't added until vue-demi 0.13, and kv-components is still using 0.12.
> fix: upgrade to latest vue-demi to support vue 2.7

- @kiva/kv-components/utils/loanCard.js
https://kiva.atlassian.net/browse/MP-170
- Loan card callout categories were missing props to make them clickable
> fix: category callouts were missing props to make them clickable

- @kiva/kv-components/package.json
- @kiva/kv-tokens/configs/tailwind.config.cjs
- @kiva/kv-tokens/package.json
- package-lock.json
Updates tailwind, remove line-clamp plugin since line-clamp has been merged into tailwind base. Gets rid of this warning everywhere: 
```As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.```
> chore: update tailwind, remove line-clamp plugin

- .github/workflows/chromatic.yml
- @kiva/kv-shop/src/oneTimeCheckout.ts
For some in-context checkout scenarios such as impact-dashboards we do not want to redirect to our standard thanks page.
> fix: add option to deactivateRedirect to executeOnetimeCheckout method

- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/stories/KvLendCta.stories.js
Fixes issue with button still navigating when a secondary button handler is supplied, updated story.
Logic is: 
If secondary button handler exists, execute it. 
If secondary button handler does not exist, run handleCheckoutFunction (for tracking) and navigate
> fix: loan card button secondary action and destination

- @kiva/kv-loan-filters/src/dafEligible.ts
- @kiva/kv-loan-filters/src/tests/dafEligible.spec.ts
- @kiva/kv-loan-filters/src/tests/fixtures/mockLoanSearchData.ts
This shoud ensure we can apply `dafEligible` to flss filters that use these utils.
I've got a separate set of work in CPS that includes this as part of the defaultLoanSearchState as well.
> feat: add dafEligible as a valid loan filter for flss

- @kiva/kv-components/utils/loanCard.js
- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvWideLoanCard.vue
- @kiva/kv-components/vue/stories/KvClassicLoanCard.stories.js
We need a way to control what happens when you click on the card elements (the image, the loan-use, the progress meter). I wanted to avoid adding yet another prop. This makes it so that if the prop "custom-loan-details" is true, emit an event instead of navigating. 
I'm pretty confident this prop is not used anywhere, and was just copied over from: `src/components/LoanCards/KivaClassicBasicLoanCard.vue`, I searched and could not find a use of it. Also, the previous use of `this.$emit` was throwing an error and not working. this fixes that
> feat: implement custom loan details on loan card

- @kiva/kv-components/utils/loanCard.js
- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvWideLoanCard.vue
Event was firing twice because there was a click handler on the borrower image wrapper element and the image element. Now that we are listening to this event and either suppressing it or navigating on the various `readMore` click handlers, we actually don't need this event, it does the same thing.
> fix: event is firing twice

- @kiva/kv-shop/src/basket.ts
- @kiva/kv-shop/src/basketCredits.ts
- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/basketTotals.ts
- @kiva/kv-shop/src/checkoutStatus.ts
- @kiva/kv-shop/src/managedAccount.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/receipt.ts
- @kiva/kv-shop/src/shopQueries.ts
- @kiva/kv-shop/src/subscriptionCheckout.ts
- @kiva/kv-shop/src/useBraintreeDropIn.ts
- @kiva/kv-shop/src/validatePreCheckout.ts
- Apparently this is a known issue with using the Apollo package within an ES module
- The Vue migration converted the `ui` repo to an ES module, so this changeset is needed (checkout page currently crashes the dev server 😄 )
> fix: use auth0 package file name to be compatible with es modules

- @kiva/kv-components/vue/KvContentfulImg.vue
- @kiva/kv-components/vue/stories/KvContentfulImg.stories.js
Contentful will not serve images with a single dimension > 4000 px. This came up again. Usually an issue on retina screens when we build the 2x url. I made a similar fix for the responsive image sets in cps, but we need this fix for embedded images.  This seems to be coming up lately because the imported images from the legacy blog are huge, and we are linking to blog entries in other contexts for example the new us-hubs page
> fix: max dimensions on kvContentfulImg

- @kiva/kv-components/vue/KvContentfulImg.vue
Some folks noticed that small contentful based images were looking blurry so we investigated together and found the hard-coded quality setting has a degrading affect on smaller images...
This update uses the width if available to increase the quality for 1x images smaller than 200px. I haven't seen a need to change the quality on 2x images but we may want to increase a bit there too.
Small 124x124
[https://images.ctfassets.net/j0p9a6ql0rn7/5stTWA7prb8ckIYXxewWvr/addf80c6ea2bdd050de066[…]uote_Photo.png?w=124&h=124&fit=scale&f=center&fm=webp&q=80](https://images.ctfassets.net/j0p9a6ql0rn7/5stTWA7prb8ckIYXxewWvr/addf80c6ea2bdd050de066ff53cf7692/CLEAN_quote_Photo.png?w=124&h=124&fit=scale&f=center&fm=webp&q=80)
[https://images.ctfassets.net/j0p9a6ql0rn7/5stTWA7prb8ckIYXxewWvr/addf80c6ea2bdd050 …
> fix: increase quality setting for small contentful images

- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
- @kiva/kv-components/vue/KvWideLoanCard.vue
Our cypress tests search through collections of loan cards to target specific states. This will make sure there is always a way to find a list of loan cards on a page across any usages of these components.
> chore: add loan-card class to all loan cards for cypress test access

- .eslintrc.cjs
- @kiva/kv-components/vue/.storybook/main.js
- @kiva/kv-components/vue/KvFlag.vue
- package-lock.json
- package.json
https://kiva.atlassian.net/browse/MP-607
- The relative path to `node_modules` didn't work when imported into a different repo
- I went with the alias we are already using in CPS
> fix: relative node_modules path broke when imported into another app

- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
https://kiva.atlassian.net/browse/MP-607
- Fixed some styling issues I noticed when integrating into CPS
- Image now uses an existing size in Cloudinary (500 x 250 px) -> this is larger than we need, but it's not too far off and has the correct aspect ratio (~1/2), the image was blurry and zoomed incorrectly before
- The height of the card was cutting off the content a little and removing padding from the bottom
- The progress bar wasn't always at the bottom of the card
> fix: adjust new card styling

- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
https://kiva.atlassian.net/browse/MP-607
- Turns out the previous size didn't have a retina size available in existing cloudinary sizes -> you would get black bars on the sides of the image in mobile (or chrome emulator)
- This size is slightly different ratio, but it should look pretty close
- The size used here has a retina size
> fix: use an image size we already have a retina size for

- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
https://kiva.atlassian.net/browse/MP-607
- Moving TW classes to be inline makes it easier to override from parent app
> fix: use TW class inline to make override simpler

- @kiva/kv-components/vue/KvLightbox.vue
- Fixed issue in `ui` `vue-3` branch where the lightbox ref was `null`
- Simple `nextTick` usage
- Verified functionality locally, will test again in `main` branch
> fix: resolve issue found in ui vue migration

- @kiva/kv-components/vue/KvTreeMapChart.vue
- The Vue 3 branch of `ui` didn't like the previous way we were importing
- Ensured this still works in storybook
> fix: resolve chart issue with vue 3

- @kiva/kv-components/package.json
- @kiva/kv-components/vue/KvTreeMapChart.vue
- package-lock.json
- Vite was having issues importing the treemap package in the `vue-3` branch of `ui`
- This uses a new fork I created of the treemap package that converts the package to the module type
https://github.com/kiva/treemap
> feat: use kiva fork of treemap repo

- @kiva/kv-components/vue/KvThemeProvider.vue
- @kiva/kv-components/vue/stories/KvThemeProvider.stories.js
There is a need to underline the h3 styles on the call to actions on the impact dashboard
> feat: add underline styles for h3

- @kiva/kv-components/vue/KvSelect.vue
https://kiva.atlassian.net/browse/MP-855
- I had already fixed this for ui `KvSelect` but hadn't encountered this issue with the components `KvSelect` yet
- Basically we have to change how `v-model` vs `value` is handled for the latest Vue 3
- Tested this directly in the `node_modules` folder in `ui` locally
> fix: change how model value is handled for select component

- @kiva/kv-components/vue/KvPieChart.vue
The `activeSlice === slice` comparison in the template works in Vue 2, but in Vue 3 `activeSlice` is actually a Ref of the slice and so `activeSlice.value` needs to be compared instead. For compatibility with Vue 2, I moved the comparison out of the template and into a method.
I also change the check for the large slice to be for slices larger than 99% rather than exactly 100%, to account for any rounding of numbers less than 100 that might result in the slice not displaying.
> fix: pie chart not animating in vue 3

- @kiva/kv-components/vue/KvPieChart.vue
Pie chart slice animation was still not working, due to vue 3 reference objects being Proxies. Vue provides the `toRaw` method to unwrap those proxies and access (but not modify) the original object. Confirmed working in UI with vue 3 locally.
> fix: activeSlice value isn't comparable because it's a Proxy, use toRaw

- @kiva/kv-shop/src/components/KvPaymentSelect.vue
https://kiva.atlassian.net/browse/MP-994
- Moved braintree helper text to component library
> fix: centralize braintree helper text

- .github/workflows/chromatic.yml
- .github/workflows/npm-release.yml
- @kiva/kv-components/vue/.storybook/main.js
- @kiva/kv-components/vue/KvButton.vue
- @kiva/kv-components/vue/KvClassicLoanCard.vue
- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
- @kiva/kv-components/vue/KvTab.vue
- @kiva/kv-components/vue/KvTabs.vue
- @kiva/kv-components/vue/KvTextInput.vue
- @kiva/kv-components/vue/KvWideLoanCard.vue
- @kiva/kv-components/vue/stories/KvThemeProvider.stories.js
- @kiva/kv-components/vue/stories/StyleguideProse.stories.js
- @kiva/kv-tokens/build/build.cjs
- @kiva/kv-tokens/configs/kivaColors.cjs
- @kiva/kv-tokens/configs/kivaHeadingUnderline.cjs
- @kiva/kv-tokens/configs/kivaTypography.cjs
- @kiva/kv-tokens/configs/tailwind.config.cjs
- @kiva/kv-tokens/package.json
- @kiva/kv-tokens/primitives.json
- package.json
Initial pass at ecosystem themes to create a working storybook link for refining theme tokens.
Includes:
- color updates for stone-3 and marigold-3
- underline styling for links
- updated default theme
- 5 new ecosystem-based themes
- tweaks to KvButton color classes for button variants
- tweaks to KvTextInput color classes
There is very limited usage of existing themes throughout the site. Where they are used, they are only used for their background color and text color, so this won't change how those sections appear. We will replace those usages in follow-up design-debt tasks.
> feat: initial styles for ecosystem themes

- @kiva/kv-components/package.json
All files that can be imported from a package need to be declared in the package.json exports. the tailwind config is imported here https://github.com/kiva/ui/blob/main/tailwind.config.js#L1
> fix: add tailwind config to kv-components exports

- @kiva/kv-tokens/build/build.cjs
- @kiva/kv-tokens/configs/util.cjs
This adds a script that generates this file for us https://github.com/kiva/kiva/blob/development/sites/www_kiva/styleguide/source/css/scss/tw-exported-vars.scss
Like other monolith styles, we'll need to manually update this file in the monolith when there are changes.
> feat(kv-tokens): generate scss variables from primitives.json during build

- @kiva/kv-components/vue/KvSideSheet.vue
- @kiva/kv-components/vue/stories/KvSideSheet.stories.js
- Smoothed side sheet animation slightly by removing changing padding
- Added y overflow in case content is larger than parent (content was hidden, for example, when testing in storybook with the image I added)
> fix: small side sheet fixes

- @kiva/kv-components/package.json
- @kiva/kv-components/utils/carousels.js
- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/KvVerticalCarousel.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
- @kiva/kv-components/vue/stories/KvVerticalCarousel.stories.js
- package-lock.json
* Adds fade plugin -- initialized via `:fade-enabled="true"`
* Adds autoplay plugin initialized via: `:autoplay-options="{ playOnInit: true, delay: 3000 }"` (for example)
See stories for use, theres some trickyness to get the auto playing status and trigger autoplay outside of the carousel, mostly related to when the carousel is initialized and the fact that most carousel interactions actually pause the auto play behavior
> feat: add autoplay and fade plugin options for carousels

- @kiva/kv-tokens/configs/kivaTypography.cjs
UI and CPS are pre-loading fonts while using `https://www.kiva.org` as the cdn url. Because this config is still using the a different url (the fastly freetls url) for the cdn, the fonts are re-downloaded when the tailwind css is parsed. Making the urls match fixes this (confirmed locally with CPS).
I also found that UI is generating different font files now. This doesn't cause the same re-downloading issue, because on UI pages the tailwind css is placed first, so the UI font-face rules override the tailwind ones and the urls from the tailwind css are ignored. I think a good follow-up task to this is centralizing the font files and definitions in kv-tokens, but this quick fix will address the font re-downloading issue in CPS for now.
> fix: update font cdn url

- .github/workflows/run-ui-tests.yml
- @kiva/kv-components/utils/carousels.js
- @kiva/kv-components/vue/KvVerticalCarousel.vue
- @kiva/kv-components/vue/stories/KvCarousel.stories.js
- @kiva/kv-components/vue/stories/KvVerticalCarousel.stories.js
Adds play/pause button to vertical carousel.
Modify carousel functionality a bit to allow for:
- the play/pause button to work
- the ability to play/pause from outside the carousel
- the ability to read the play/pause state from outside the carousel
Mobile alignment of buttons:
Desktop alignment of buttons:
I did not add the play/pause button to the regular carousel. I'm not sure we have a design of where it should go.
> feat: add autoplay button if autoplay plugin is enabled

- @kiva/kv-components/utils/carousels.js
- @kiva/kv-components/vue/stories/KvVerticalCarousel.stories.js
Ran into some more issues when trying to implement this. 
Embla docs say autoplay should stop by default on carousel interactions, but I found that to not be the case with our setup. This makes sure the autoplay stops when goToSlide is called, either from within the carousel itself or from external components. Also remove log statements
> feat: make sure autoplay stops on carousel interactions

- @kiva/kv-components/vue/KvCommentsAdd.vue
- @kiva/kv-components/vue/KvCommentsHeartButton.vue
- @kiva/kv-components/vue/KvCommentsReplyButton.vue
- @kiva/kv-components/vue/KvInlineActivityCard.vue
- @kiva/kv-components/vue/KvIntroductionLoanCard.vue
- @kiva/kv-components/vue/KvLendCta.vue
- @kiva/kv-components/vue/KvLoanActivities.vue
- @kiva/kv-components/vue/KvWideLoanCard.vue
Addressing build warnings like
```
[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.
```
> refactor: update deep selectors

- @kiva/kv-components/utils/carousels.js
- @kiva/kv-components/vue/stories/KvVerticalCarousel.stories.js
I had a hard time getting autoplay to work in the context of our impact-dashboard globe. This fixes those issues. 
1. Remove `clickAllowed` method - this was deprecated in embla here: https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc01 - embla now handles this automatically. 
2. Remove extra autoplay stop code in `handleUserInteraction` - We just need this in the `goToSlide` function
3. Create a story to replicate issue on impact dashboard, add fixes for this scenario
The Issue:
The problem has to do with the way the slides in the impact-dashboard change dimensions when selected. When the slide dimensions are changed, embla now automatically fires a reInit event. When the carousel was reInit, the autoplay `playOnInit` setting was reset to whatever the initial value …
> fix: carousel autoplay issues

- @kiva/kv-components/utils/carousels.js
- @kiva/kv-components/vue/KvCarousel.vue
- @kiva/kv-components/vue/KvVerticalCarousel.vue
I removed clickAllowed from onCarouselContainerClick but now the clicks arent triggering inside the slides. Embla now handles what was our `onCarouselContainerClick` logic, so we can just remove all of this to get clicks working again.
> fix: click events after removal of clickAllowed

- @kiva/kv-components/build/libCss.js
- @kiva/kv-components/vite.config.js
Vite library mode does not include imports for generated css files (see https://github.com/vitejs/vite/issues/1579), and instead requires library users to manually import every needed css file. This PR avoids that by using a custom vite plugin to replace the placeholder comment for the css file with an import line. The plugin is based on the various plugins that have already been created to deal with this issue, but tailored for our needs.
> fix(kv-components): include import line for component css files

- @kiva/kv-components/src/vue/KvLendCta.vue
https://kiva.atlassian.net/browse/MP-1306
- The "preset options" variation of the lend CTA was always choosing the dropdown value, regardless of whether the user clicked one of the value buttons after changing the dropdown
- Refactored to use constant for magic string
> fix: resolve issue where preset options dropdown needed to be reset

- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/tests/basketItems.spec.ts
Adds new input to this mutation which will allow us to "tag" donations with a metadata string.
> feat: add metadata input to donation mutation

- @kiva/kv-shop/src/basketItems.ts
Getting a ""message": "Cannot query field \"metadata\" on type \"Donation\"."," 
Which I see we aren't adding it to the response. Which is fine, I don't need the metadata on the response.
> fix: can't query metadata in response

- @kiva/kv-components/package.json
- @kiva/kv-shop/.eslintrc.cjs
- @kiva/kv-shop/package.json
- @kiva/kv-shop/src/basket.ts
- @kiva/kv-shop/src/basketCredits.ts
- @kiva/kv-shop/src/basketItems.ts
- @kiva/kv-shop/src/basketTotals.ts
- @kiva/kv-shop/src/checkoutStatus.ts
- @kiva/kv-shop/src/components/KvPaymentSelect.vue
- @kiva/kv-shop/src/index.ts
- @kiva/kv-shop/src/managedAccount.ts
- @kiva/kv-shop/src/oneTimeCheckout.ts
- @kiva/kv-shop/src/receipt.ts
- @kiva/kv-shop/src/shopQueries.ts
- @kiva/kv-shop/src/subscriptionCheckout.ts
- @kiva/kv-shop/src/useBraintreeDropIn.ts
- @kiva/kv-shop/src/validatePreCheckout.ts
- @kiva/kv-shop/vite.config.ts
- @kiva/vite-plugin-vue-lib-css/README.md
- @kiva/vite-plugin-vue-lib-css/index.js
- @kiva/vite-plugin-vue-lib-css/package.json
- lerna.json
- package-lock.json
- package.json
This bundles the braintree web drop in with kv-shop to make it work in vite dev mode in consumer projects.
Created a package for `@kiva/vite-plugin-vue-lib-css` so that the plugin can be shared between kv-components and kv-shop.
Known issues:
- Typescript complains about not recognizing `@kiva/kv-components` due to kv-components not having any type declarations. This likely could be addressed by setting up kv-components for typescript and adding a type definition generation step similar to how this PR is using vite-plugin-dts.
> feat(kv-shop)!: compile kv-shop with vite

- @kiva/kv-shop/src/useBraintreeDropIn.ts
- @kiva/kv-shop/vite.config.ts
Trying to address this error from the dropin import line:
> Cannot destructure property 'default' of '(intermediate value)' as it is undefined.
> fix: use commonjs braintree dropin instead of amd browser build

- @kiva/kv-shop/package.json
- @kiva/kv-shop/vite.config.ts
Main issue seen on the donate page appears to be from running vite/rollup twice on kv-shop (once in this repo for the node module, and a second time in CPS or UI). Exports are renamed but where they are imported is not renamed. Confirmed that forcing CPS to build the drop-in instead resolves the issue.
We probably could have stuck with tsup and just changed the braintree import line to `await import('braintree-web-drop-in/index.js')` to resolve the original issue we encountered when using the drop-in locally 🤷
> fix(kv-shop): require braintree-web-drop-in as a peer dependency

- @kiva/kv-components/src/vue/KvCartModal.vue
- @kiva/kv-components/src/vue/stories/KvCartModal.stories.js
- As we are not able to conditional rendering on a template element, passing this to slot content.
> fix: kv cart modal slot fix

- @kiva/kv-shop/src/useBraintreeDropIn.ts
I tested this in CPS by editing the file in my node modules/@kiva/kv-shop there directly, this seems to work. I also ran the build in kv-ui-elements and that also builds fine. 
@emuvente Thoughts on this? Seems a bit silly that the fix is so minor. Am I missing anything here? Is there any way to test the build version in CPS more directly?
> fix: fix for braintree drop in error in local dev

- @kiva/kv-components/src/vue/KvLendCta.vue
For the in-context BP in the impact dashboard, we want to use the `showPresetAmounts` and also show the secondary button text, this is not possible at the moment. 
I looked around the codebase for uses of showPresetAmounts and I believe this is a safe change to make.
> feat: add secondary button text with show presets

- @kiva/kv-components/src/vue/KvLendCta.vue
Reverts kiva/kv-ui-elements#545
Actually `this.secondaryButtonText`  always has a default value, so this will prevent `Continue to basket` from ever showing. My bad
> Revert "feat: add secondary button text with show presets"

- @kiva/kv-components/src/vue/KvLendCta.vue
Ok trying this again. 
if secondaryButtonText prop value exists, always return that, else, show `'Continue to basket'` if showPresets, or `'Checkout now'` if no showPresets
> feat: change secondary text logic on lendcta

- @kiva/kv-components/src/vue/.storybook/preview.js
- @kiva/kv-components/src/vue/KvUserAvatar.vue
I noticed any PR is generating a lot of excessive diffs in chromatic. This is mostly due to KvUserAvatar using random colors for the user letter and circle background, so all stories that use that component will generate diffs in every PR. 
This will ignore the random color/backgrounds for the purposes of chromatics diff. 
Note, a diff will still be generated if the avatar changes in size
https://www.chromatic.com/docs/ignoring-elements/
> feat: ignore kvuseravatar in chromatic

- @kiva/kv-loan-filters/src/filterUtils.ts
- @kiva/kv-loan-filters/src/trusteeId.ts
🤦  This is required for the new filters to be available to the getValidatedSearchState methods. For the time being, none fo these will be exposed in the UI so I've kept them out of UI configs.
> fix: add new filters to filterUtils and fix facet key on trusteeId

- @kiva/kv-components/src/utils/imageUtils.js
- @kiva/kv-components/src/utils/loanCard.js
- @kiva/kv-components/src/vue/.storybook/preview.js
- @kiva/kv-components/src/vue/KvUserAvatar.vue
- @kiva/kv-components/src/vue/stories/KvMap.stories.js
- @kiva/kv-components/tests/unit/specs/utils/imageUtils.spec.js
Making these methods use consistent 'random' values avoids client-side hydration mis-matches caused by different random values returned on the server and the client. This will also make the stories using loan callouts and user avatars consistent, so they will no longer show up as false-positives in chromatic.
The end result is that users will have a consistent avatar instead of it changing on every page load, and loan cards will only display different random callouts when their fundraising progress changes.
> feat: use Alea to get consistent 'random' value for loan callouts and user avatars

- @kiva/kv-components/src/vue/KvSideSheet.vue
- @kiva/kv-components/src/vue/stories/KvSideSheet.stories.js
- Made the back button optional via a prop. 
- Removed misspelled classes which werent having an effect anyway.
- Modified stories to work with storybook controls
For our context in the impact dashboard and for the upcoming badge journeys, the back button should be optional
> feat: make sidesheet back button optional

- @kiva/kv-components/src/vue/KvSideSheet.vue
Adds a new prop to the SideSheet component to allow for the Headline border to be hidden if specified. Also reduces the y padding on the headline slightly to conform to latest Figma designs.
> fix: improve SideSheet component for BadgeJourneys

- @kiva/kv-components/src/vue/KvSideSheet.vue
- @kiva/kv-components/src/vue/stories/KvSideSheet.stories.js
Adds the `widthDimensions` prop to the `KvSideSheet` component in order to bring the component fully in line to Figma mock standards.
In the process it also slightly modifies the transition timings in order to improve the out transition.
> feat: add widthDimensions prop to KvSideSheet

- @kiva/kv-components/src/vue/KvTooltip.vue
- @kiva/kv-components/src/vue/stories/KvTooltip.stories.js
Previously we weren't importing or mapping the `default` theme for our KvToolTip. That theme is supposed to be used by "default" so it's always selected. _It's a bit of a long-shot to think this will fix the issue with using it in rtp-nuxt but it might!_
Otherwise, we now import the default theme and map it. I've also imported and mapped all our new themes and updated the story with a selector control so you can test them all out. Also, made a fix for the arrow color which wasn't getting applied.
> fix: ensure we import and map default theme on KvToolTip, add new themes

- @kiva/kv-components/src/vue/KvCardFrame.vue
- @kiva/kv-components/src/vue/index.js
- @kiva/kv-components/src/vue/stories/KvCardFrame.stories.js
We've been making a lot of content cards and there are more coming. This component is a configurable frame that allows customizing a card-like container. Content is recieved by a slot so can be anything.
- Allows setting one of our newer approved themes
- Allows passing in the backround, border, shadow and rounded classes you'd like used for the frame.
A few stories to illustrate, [Interact with them in the storybook build](https://608b4cf87f686c00213841b1-vesohuzdzu.chromatic.com/?path=/docs/kvcardframe--kv-components)
Default:
Custom Theme, Border, Background + Shadow
Custom Theme + Background, No Border, No Shadow
Full Bleed Image as a link:
> Feat content card frame

- @kiva/kv-tokens/primitives.js
Updates our default radius setting from 14 to 16 to align with latest design system updates. Noting there will be additional standard updates in the near future that will expand our radius options.
> chore: update default radius to 16 from 14

- @kiva/kv-loan-filters/src/categories.ts
Reference: https://github.com/kiva/cms-page-server/pull/2199#discussion_r2263563857
Moving forward with solution in which categories.ts contains radio group options thus RadioGroupFilter.vue in cms-page-server repo will be reverted back to its original state!
> feat: applying radio group filter to categories filters

- @kiva/kv-components/src/vue/KvCheckbox.vue
- @kiva/kv-components/src/vue/KvCheckoutReceipt.vue
- @kiva/kv-components/src/vue/KvInlineActivityCard.vue
- @kiva/kv-components/src/vue/KvLoadingPlaceholder.vue
- @kiva/kv-components/src/vue/KvTextInput.vue
- @kiva/kv-components/src/vue/KvTreeMapChart.vue
- @kiva/kv-components/src/vue/stories/KvCardFrame.stories.js
- @kiva/kv-components/src/vue/stories/KvMaterialIcon.stories.js
Updates prior usages of the `sm` radius to be `xs` which is our new 4px variable.
Also verified that storybook sizes are correct now:
> fix: migrate prior sm radii usages to be xs to restore the 4px radius

- @kiva/kv-components/src/vue/KvTooltip.vue
I need to be able to control the sizing and placement of the tooltip for some specific Viva contexts. This makes the popper options and the max width of KvTooltip configurable, using the current values as defaults.
> feat(KvTooltip): configurable max-width and popper options

- @kiva/kv-components/src/vue/KvWwwHeader.vue
- @kiva/kv-components/src/vue/KvWwwHeader/KvHeaderLinkBar.vue
https://kiva.atlassian.net/browse/MP-2028
- Mobile was still navigating on Lend click/tap, thinking it might be because window isn't guaranteed to be defined in onBeforeMount
- Removed some extra padding I recently added from desktop (stays in mobile)
> fix: more nav tweaks

- @kiva/kv-components/src/vue/KvLendCta.vue
This update adds responsive support to the KvLendCta component by tracking the actual container width with a ResizeObserver, introducing the isNarrowComponent method, and conditionally rendering the CTA button in a second row when the component is narrow, ensuring only one CTA is visible and maintaining a clean layout across all container sizes.
> Fix mp 1988 narrow lend cta

- @kiva/kv-components/src/vue/KvCheckoutReceipt.vue
- @kiva/kv-components/src/vue/KvDatePicker.vue
- @kiva/kv-components/src/vue/stories/KvCheckoutReceipt.stories.js
- @kiva/kv-components/src/vue/stories/KvDatePicker.stories.js
* We won't need to require a lender for a guest receipt. 
* datepicker was throwing several vue warns
- placeholder should come from v-bind="$args"
- event names for open/close were incorrect
> fix: don't require lender for receipt, fix datepicker

- @kiva/kv-components/src/vue/stories/StyleguidePrimitives.stories.js
- @kiva/kv-tokens/configs/kivaTypography.js
- @kiva/kv-tokens/configs/tailwind.config.js
- @kiva/kv-tokens/primitives.js
This PR introduces fallback font styles for PostGrotesk and Dovetail MVB with adjustments to match the primary font style in size as closely possible. This minimizes layout shift and repaints, improving performance. See https://developer.chrome.com/blog/font-fallbacks for more details
The fallback font can't match the size of the primary font perfectly, because the exact sizing adjustments differ based on the content of the text. Instead, this uses the average character width, weighted against their occurrence in English. I used the calculation provided by [Capsize](https://seek-oss.github.io/capsize/) for this PR. I also added the ability to switch which pangram is used for displaying text styles in the primitives story, so that the difference between different text content can be seen.
> feat: fallback font styles adjusted to match primary styles

- @kiva/kv-components/src/vue/KvClassicLoanCard.vue
Tracking down Apollo cache conflicts and `gender` fields seems central to the issues. We use `gender` in ATB modal, which is now a permanent feature, so we might as well add it to the shared fragment for multiple reasons.
> fix: add gender to loan card data to simplify where the fragment is used

- @kiva/kv-shop/src/givingFunds.ts
The aggregate shop errors are all returned in aggregate which makes them really hard to display to the user. We do this in checkout, but I think for addGivingFund we can just return the first error. 
After this fix and upcoming PR in cps:
> feat: remove aggregate errors for add giving fund
